package com.kmaebashi.samplan.util;

public enum ErrorMessage {
    INVALID_CHARACTER,
    INVALID_ESCAPE_CHARACTER_IN_STRING,
    UNEXPECTED_TOKEN,
    TYPE_EXPECTED,
    VARIABLE_DUPLICATION,
    VARIABLE_NOT_FOUND,
    TYPE_MISMATCH_MATH,
    TYPE_MISMATCH_BOOLEAN,
    INC_DEC_NOT_LVALUE,
    INC_DEC_NOT_INT,
    TYPE_MISMATCH,
    ASSIGN_NOT_LVALUE,
    RETURN_OUT_OF_FUNCTION,
    FUNCTION_DUPLICATION,
    FUNCTION_NOT_FOUND,
    FUNCTION_ARG_COUNT_MISMATCH,
    FUNCTION_ARG_TYPE_MISMATCH
}
